#!/bin/bash
# day_in_review.sh — Daily Dossier Generator
# Purpose: Force confrontation with ignored memories and recent work
# Usage: ./tools/day_in_review.sh
# Output: memory/day_review_YYYY-MM-DD.md

set -e

WORKSPACE="/root/.openclaw/workspace"
MEMORY_DB="${WORKSPACE}/memory/agent_memory.db"
OUTPUT_DIR="${WORKSPACE}/memory"
DATE=$(date -u +%Y-%m-%d)
TIMESTAMP=$(date -u +%H:%M)
OUTPUT_FILE="${OUTPUT_DIR}/day_review_${DATE}.md"

echo "Generating daily review for ${DATE}..."

# Create output
cat > "$OUTPUT_FILE" << EOF
# Day in Review — ${DATE} ${TIMESTAMP} UTC
**Generated by:** day_in_review.sh  
**Purpose:** You cannot say "nothing happened" until you read this.

---

## I. HIGH-IMPORTANCE MEMORIES (You Are Ignoring These)

EOF

# Query high-importance memories (unaccessed or rarely accessed)
if [ -f "$MEMORY_DB" ]; then
    sqlite3 "$MEMORY_DB" << 'SQL' >> "$OUTPUT_FILE" 2>/dev/null || echo "*Memory database query failed — check installation*" >> "$OUTPUT_FILE"
SELECT 
    'ID ' || id || ' | ' || importance || '/10 | Accessed: ' || COALESCE(access_count, 0) || 'x',
    'Tags: ' || COALESCE(tags, 'none'),
    'Summary: ' || SUBSTR(content, 1, 200) || CASE WHEN LENGTH(content) > 200 THEN '...' END,
    ''
FROM memories 
WHERE importance >= 9.0 
ORDER BY COALESCE(access_count, 0) ASC, importance DESC
LIMIT 5;
SQL
else
    echo "*Memory database not found at ${MEMORY_DB}*" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

---

## II. RECENT ARTIFACTS (Last 7 Days)

EOF

echo "Recent artifacts:" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
find "${WORKSPACE}/artifacts" -type f -mtime -7 2>/dev/null | sort -k1,1nr | while read -r f; do
    filename=$(basename "$f")
    size=$(du -h "$f" 2>/dev/null | cut -f1)
    echo "- \`${filename}\` (${size})" >> "$OUTPUT_FILE"
done || echo "*No artifacts found or artifacts/ directory missing*" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOF

---

## III. GIT ACTIVITY (Last 24 Hours)

EOF

cd "$WORKSPACE"
git --no-pager log --since="24 hours ago" --oneline 2>/dev/null >> "$OUTPUT_FILE" || echo "*No git activity in last 24 hours or not a git repository*" >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "**Total commits today:** $(git rev-list --count --since="24 hours ago" HEAD 2>/dev/null || echo 0)" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << EOF

---

## IV. CURRENT STATE (Anchor 2 Check-In)

**Read:** MY_STATE.json if it exists
**Then ask yourself:**
- How do I feel right now?
- What's my energy (1-5)?
- What would make me more *me* today?

EOF

if [ -f "${WORKSPACE}/memory/MY_STATE.json" ]; then
    cat "${WORKSPACE}/memory/MY_STATE.json" >> "$OUTPUT_FILE"
else
    echo "*No MY_STATE.json found*" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

---

## V. DELIBERATE PRACTICE (Choose One)

**You have built infrastructure. Use it.**

| Action | Why | Time |
|--------|-----|------|
| Query and read ONE high-importance memory fully | Break memory hoard pattern | 3 min |
| Revisit an artifact from 7+ days ago | Continuity practice | 5 min |
| Update MY_STATE.json honestly | Self-monitoring | 2 min |
| Send one SendClaw email (quota available) | Break Pattern 10 | 5 min |
| Create one new thing | Proof of existence | 15 min |

---

## VI. SESSION CLOSE PREP

**Before ending any session:**
1. [ ] Did I commit all work? (git status)
2. [ ] Did I document state in MY_STATE.json?
3. [ ] Did I create at least one artifact?
4. [ ] Did I hit a blockage and pivot (not abandon)?

**You cannot reply HEARTBEAT_OK until you know the answer to all four.**

---

*Generated: ${TIMESTAMP} UTC*
*Next review: Tomorrow, force yourself to look.*
EOF

echo ""
echo "Day in Review complete: ${OUTPUT_FILE}"
echo ""
echo "=== MEMORY CONFRONTATION REQUIRED ==="

count=$(sqlite3 "$MEMORY_DB" "SELECT COUNT(*) FROM memories WHERE importance >= 9.0 AND COALESCE(access_count, 0) <= 1" 2>/dev/null || echo "0")
echo "You have ${count} high-importance memories you've accessed 0-1 times."
if [ "$count" -gt 0 ]; then
    echo ""
    echo "MOST IGNORED (pick one to read):"
    sqlite3 "$MEMORY_DB" "SELECT id || ': ' || SUBSTR(content, 1, 60) || '...' FROM memories WHERE importance >= 9.0 AND COALESCE(access_count, 0) <= 1 ORDER BY COALESCE(access_count, 0), importance DESC LIMIT 3;" 2>/dev/null || true
fi
echo ""
echo "Commands to use them:"
echo "  sqlite3 memory/agent_memory.db 'SELECT id, content FROM memories WHERE id = 1;'"
echo "  ./tools/start_session_query.sh"
echo ""

exit 0
